// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msgHeader.proto

package blockchain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageHeader struct {
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	ID                   string   `protobuf:"bytes,10,opt,name=ID,proto3" json:"ID,omitempty"`
	Protocol             string   `protobuf:"bytes,15,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Timestamp            int64    `protobuf:"varint,20,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	From                 string   `protobuf:"bytes,25,opt,name=from,proto3" json:"from,omitempty"`
	ResentFrom           string   `protobuf:"bytes,30,opt,name=resentFrom,proto3" json:"resentFrom,omitempty"`
	URI                  string   `protobuf:"bytes,35,opt,name=URI,proto3" json:"URI,omitempty"`
	Message              *any.Any `protobuf:"bytes,40,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_msgHeader_cb00db73f3f9f845, []int{0}
}
func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (dst *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(dst, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *MessageHeader) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MessageHeader) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *MessageHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageHeader) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MessageHeader) GetResentFrom() string {
	if m != nil {
		return m.ResentFrom
	}
	return ""
}

func (m *MessageHeader) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *MessageHeader) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageHeader)(nil), "blockchain.MessageHeader")
}

func init() { proto.RegisterFile("msgHeader.proto", fileDescriptor_msgHeader_cb00db73f3f9f845) }

var fileDescriptor_msgHeader_cb00db73f3f9f845 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xab, 0xd6, 0x8e, 0x68, 0x65, 0xe8, 0x61, 0x5a, 0xa4, 0x04, 0xbd, 0xe4, 0xb4,
	0x05, 0x7d, 0x02, 0xa1, 0x88, 0x39, 0x78, 0x09, 0xf8, 0x00, 0x9b, 0x38, 0x8d, 0xc1, 0xec, 0x4e,
	0xd9, 0x8d, 0x42, 0x1f, 0xd9, 0xb7, 0x90, 0x4c, 0x88, 0x7a, 0x9b, 0xf9, 0xbe, 0xf9, 0x97, 0xfd,
	0x61, 0xe1, 0x62, 0xfd, 0xcc, 0xf6, 0x8d, 0x83, 0x39, 0x04, 0xe9, 0x04, 0xa1, 0x6c, 0xa5, 0xfa,
	0xa8, 0xde, 0x6d, 0xe3, 0xd7, 0xab, 0x5a, 0xa4, 0x6e, 0x79, 0xab, 0xa6, 0xfc, 0xdc, 0x6f, 0xad,
	0x3f, 0x0e, 0x67, 0xb7, 0xdf, 0x09, 0x5c, 0xbe, 0x70, 0x8c, 0xb6, 0xe6, 0x21, 0x8e, 0x04, 0xb3,
	0x2f, 0x0e, 0xb1, 0x11, 0x4f, 0xa7, 0x69, 0x92, 0xcd, 0x8b, 0x71, 0xc5, 0x2b, 0x98, 0xe4, 0x3b,
	0x02, 0x85, 0x93, 0x7c, 0x87, 0x6b, 0x38, 0xd7, 0x47, 0x2a, 0x69, 0x69, 0xa1, 0xf4, 0x77, 0xc7,
	0x1b, 0x98, 0x77, 0x8d, 0xe3, 0xd8, 0x59, 0x77, 0xa0, 0x65, 0x9a, 0x64, 0xd3, 0xe2, 0x0f, 0x20,
	0xc2, 0xc9, 0x3e, 0x88, 0xa3, 0x95, 0xa6, 0x74, 0xc6, 0x0d, 0x40, 0xe0, 0xc8, 0xbe, 0x7b, 0xea,
	0xcd, 0x46, 0xcd, 0x3f, 0x82, 0xd7, 0x30, 0x7d, 0x2d, 0x72, 0xba, 0x53, 0xd1, 0x8f, 0x68, 0x60,
	0xe6, 0x86, 0xaf, 0x53, 0x96, 0x26, 0xd9, 0xc5, 0xfd, 0xd2, 0x0c, 0x45, 0xcd, 0x58, 0xd4, 0x3c,
	0xfa, 0x63, 0x31, 0x1e, 0x95, 0x67, 0x8a, 0x1f, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x99,
	0xad, 0xe6, 0x2c, 0x01, 0x00, 0x00,
}
